name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  NODE_VERSION: "20.x"
  PYTHON_VERSION: "3.11"
  NEXT_TELEMETRY_DISABLED: "1"
  CI: "true"

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: python_backend/requirements.txt

      - name: Install backend dependencies
        run: |
          python -m venv python_backend/venv
          python_backend/venv/bin/pip install --upgrade pip
          python_backend/venv/bin/pip install -r python_backend/requirements.txt

      - name: Run backend unit tests
        run: python_backend/venv/bin/pytest -q python_backend/tests

  frontend-quality:
    name: Frontend Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install frontend dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Type-check with TypeScript
        run: npx tsc --noEmit

      - name: Build Next.js app
        run: npm run build

  integration-tests:
    name: Integration AutoTests
    runs-on: ubuntu-latest
    needs:
      - backend-tests
      - frontend-quality
    timeout-minutes: 25
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: python_backend/requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install backend dependencies
        run: |
          python -m venv python_backend/venv
          python_backend/venv/bin/pip install --upgrade pip
          python_backend/venv/bin/pip install -r python_backend/requirements.txt

      - name: Install frontend dependencies
        run: npm ci

      - name: Run end-to-end AutoTests
        env:
          PORT: 3010
          BACKEND_PORT: 5010
        run: npm run test
